const {symbol}=require('./functions.js');
const prompt=require("prompt-sync")();
const a=parseInt(prompt("enter a number:"));
const y=parseInt(prompt("enter a number:"));
const b=prompt("enter 1st string:");
const c=prompt("enter 2nd string:");
const d=prompt("enter the gender:");
const e=prompt("enter the age:");
console.log(symbol.evodd(a));
console.log(symbol.loop(a));
console.log(symbol.div(a));
console.log(symbol.addstrings(b,c));
console.log(symbol.sence(d,e));
console.log(symbol.countvowels(c));
console.log(symbol.calfact(a));
console.log(symbol.fib(a));
console.log(symbol.add(a,y));
console.log(symbol.subtract(a,y));
console.log(symbol.sum(a));